### ISSUE TITLE
Idea: Also support scheduling on Windows

### ISSUE THREAD

**Issue by dertuxmalwieder** [Geobert/emile#1]
As Windows comes with [an `at` command](https://www.windows-commandline.com/windows-at-command-examples/) that behaves similarly to the Linux one, it should be relatively easy to enhance the scheduler with `if cfg!(windows)` and a few changes in the update/remove calls.

**Comment by Geobert** [comment]
Hi, thank you for your interest, but unfortunately, I'm not using Zola anymore, so I'm not working on `emile` anymore :)

**Comment by dertuxmalwieder** [comment]
Good to know, thank you.

**Comment by Geobert** [comment]
I'm back to `zola` so I reactivated `emile`. I've totally changed how scheduling is managed so maybe you can use it on Windows too
